version: '3.3'
services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    user: root
    ports:
      - "1433:1433"
    volumes:
      - ./data/db:/var/opt/mssql/data
      - ./data/log:/var/opt/mssql/log
    
    
      
    environment:
      MSSQL_SA_PASSWORD: "Sajadsajad0101"
      ACCEPT_EULA: "Y"
      